### PR TITLE
Missing code.erb view?

### PR DESCRIPTION
**Pull request by shiffman**
@nelliemckesson could this possible be the missing view you referenced in an e-mail? (Responding there as well)

### CODE REVIEW

**Comment by shiffman** [comment]
If not maybe @runemadsen has it somewhere in his vast digital archives?

**Comment by runemadsen** [comment]
It has been a while, but as far as I remember, we used the built-in `code.erb` view located here: https://github.com/runemadsen/Magic-Book-Project/blob/master/views/code.erb. Happy to try to dig deeper if necessary :)

**Comment by nelliemckesson** [comment]
Ah yeah, I think this is it, thanks guys!

**Comment by shiffman** [comment]
I don't believe this is relevant anymore with the build process we are working on over in [noc-book-2](https://github.com/nature-of-code/noc-book-2).

**Pull request closed without merging**
