### PR TITLE
Folder strcuture fixes, typo fixes, and a few slight css tweaks

### PR DESCRIPTION
**Pull request by nelliemckesson**
@shiffman This should fix most of the stuff you pointed out in https://github.com/shiffman/The-Nature-of-Code/issues/158. Some notes:

* For the folder structure stuff, we can accomplish this within the magicbook build system, but it's going to require some folder and filename changes. I updated 3 files to illustrate what needs to happen: 

1. Each chapter file needs to live in a subfolder, named with the same number prefix currently used to determine order, and then named with whatever you want the HTML folder name to be (i.e., whatever the folder is called in the natureofcode.com repo). 
1. Then, the actual html file needs to be renamed "index.html" within that folder. See the new /00_2_dedication/, /01_chapter-1-vectors/, and /02_chapter-2-forces/ for examples. E.g.:

```
$ mkdir chapters/00_2_dedication/
$ git mv chapters/00_2_dedication.html chapters/00_2_dedication/
$ cd chapters/00_2_dedication/
$ git mv 00_2_dedication.html index.html
```

I've already updated the magicbook.json file to look for files in this folder structure, so all that's left for you to do is create and rename the rest of the folders/files.

* There was a tiny typo in the html.html layout file that was causing that preview weirdness--fixed now!

* The code is not going to look right because most of the code formatting is targeting elements that aren't current;y being added, due to the code splitting stuff.

* WHEN YOU ARE READY TO PUBLISH TO YOUR SITE: In this file: https://github.com/shiffman/The-Nature-of-Code/blob/master/layouts/html.html, update lines 7-13 and lines 26-28, replacing the ".." with "/book" (the preceding slash is important).

### CODE REVIEW

**Comment by nelliemckesson** [comment]
Not fixed: code split and syntax highlighting. Still looking into those...

**Comment by shiffman** [comment]
@joeyklee I think this likely should be merged and then we continue working from `noc-book-2`. . let me know what you think! @nelliemckesson we are actively working on this project again now that summer has arrived, we'll let you know if we have questions! Thank you for everything from last summer!

**Comment by joeyklee** [comment]
Just making a note that the changes have been merged. 

A few issues I want to keep track of here:

+ some funkiness going on with `"` and `'` quotes and double quotes

Screen Shot 2019-06-24 at 12 22 59

Screen Shot 2019-06-24 at 12 23 06

Screen Shot 2019-06-24 at 12 36 53


+ Images are not sized properly

Screen Shot 2019-06-24 at 12 40 18
Screen Shot 2019-06-24 at 12 40 30
Screen Shot 2019-06-24 at 12 40 50

**Comment by joeyklee** [comment]
@shiffman - if you run `magicbook build` feel free to also flag anything you notice. 

thanks @nelliemckesson !

**Pull request merged**
